### PR TITLE
chore: make owlbot check required

### PR DESCRIPTION
**Pull request by Neenu1995**

### CODE REVIEW

**Comment by tmatsuo** [comment]
OwlBot build log:
https://pantheon.corp.google.com/cloud-build/builds;region=global/a59cc362-922a-4699-96ac-85e676c3095b?project=repo-automation-bots

The failure is:
```
https://pantheon.corp.google.com/cloud-build/builds;region=global/a59cc362-922a-4699-96ac-85e676c3095b?project=repo-automation-bots
```

**Comment by Neenu1995** [comment]
Is this because the owlbot java image is not updated?

**Comment by tmatsuo** [comment]
I think #700 will unblock this

**Comment by tmatsuo** [comment]
I think you need to rebase

**Review by tmatsuo — APPROVED** [review]

**Review by lesv — APPROVED** [review]

**Pull request merged**
