### PR TITLE
test: adding native image configuration required for tests

### PR DESCRIPTION
**Pull request by suztomo**
Trying to fix "Kokoro - Test: Java GraalVM Native Image" build.

```
Failures (12):
  JUnit Vintage:ITSystemTest:detectLabelsTest
    MethodSource [className = 'com.google.cloud.vision.it.ITSystemTest', methodName = 'detectLabelsTest', methodParameterTypes = '']
    => java.io.FileNotFoundException: src/test/resources/wakeupcat.jpg (No such file or directory)
       com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_FileNotFoundException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
       java.io.FileInputStream.open0(FileInputStream.java)
       java.io.FileInputStream.open(FileInputStream.java:219)
       java.io.FileInputStream.<init>(FileInputStream.java:157)
       java.io.FileInputStream.<init>(FileInputStream.java:112)
       com.google.cloud.vision.it.ITSystemTest.getResponsesList(ITSystemTest.java:223)
       com.google.cloud.vision.it.ITSystemTest.detectLabelsTest(ITSystemTest.java:263)
       java.lang.reflect.Method.invoke(Method.java:566)
       org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
       org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
       [...]
...
```

https://source.cloud.google.com/results/invocations/cc541c2e-5da6-48bf-acb1-dd0d90f340b3/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-vision%2Fpresubmit%2Fgraalvm-native/log

The test execution requires some configuration for native image to load resource files.

### CODE REVIEW

**Comment by suztomo** [comment]
`{"pattern":"*.png"}` failed:

```
Fatal error:java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.png
^
```

**Comment by suztomo** [comment]
`{"pattern":".*.jpg"},` didn't make any effect.

**Comment by suztomo** [comment]
`{"pattern":"\\Qcity.jpg\\E"},` didn't work.
https://source.cloud.google.com/results/invocations/18c9ab4e-2225-4531-b777-146d0e61a1c4/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-vision%2Fpresubmit%2Fgraalvm-native/log

**Comment by suztomo** [comment]
It's from 

```
      ByteString imgBytes = ByteString.readFrom(new FileInputStream(RESOURCES + image));
```

where RESOURCES is "src/test/resources/" and image is "wakeupcat.jpg" for example. It seems the problem is the working directory.

**Comment by mpeddada1** [comment]
I think this is a limitation of using resource configs with Graal: https://github.com/mpeddada1/native-resources-config/blob/main/child-module/src/test/java/com/example/ResourceExampleTest.java. FileInputStream/FileSystems doesn't recognize the resources-config.json. What happens if we reference the resource using the ClassLoader?

**Comment by suztomo** [comment]
I recognize this is the problem of working directory https://github.com/googleapis/java-vision/pull/856#issuecomment-1079195775. JVM execution and GraalVM native-image execution show different output for working directory.

I think the integration test is intended to use file as input, rather than resources, for documentation purpose on how to use this library.

**Pull request closed without merging**
